### PR TITLE
Add playwright script to take screenshots

### PR DESCRIPTION
**Pull request by signed-long**
Takes screenshots of the login page, demo `RouteList`, and `RouteActivity`.

To run: 
```
bun playwright install webkit
bun run dev
node src/ci/screenshots.cjs http://localhost:3000
```
Also made a follow up to add them to the PR comments: https://github.com/commaai/new-connect/pull/38

RouteList-mobile
RouteList-desktop
RouteActivity-mobile
RouteActivity-desktop
Login-mobile
Login-desktop

For https://github.com/commaai/new-connect/issues/36

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Love how simple this is, though it does now introduce managing a separate Python environment now. Can we keep it this simple in JS?

**Comment by sarem-h** [comment]
is just links to the screenshot better? The PR looks cluttered

**Comment by signed-long** [comment]
> isn't just links to the screenshot better? The PR looks cluttered

This change doesn't post them to the PR comments, I just added them here to show the screenshots that the script produces. But yeah we could post links, or just make them smaller in the comment. Working on that in https://github.com/commaai/new-connect/pull/38

**Comment by adeebshihadeh** [comment]
Got this even after `bun install`. Is it expected?
```
batman:new-connect$ node src/ci/screenshots.cjs http://localhost:3000
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.launch: Executable doesn't exist at /home/batman/.cache/ms-playwright/webkit-2003/pw_run.sh
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at /home/batman/src/new-connect/src/ci/screenshots.cjs:24:39
    at Object.<anonymous> (/home/batman/src/new-connect/src/ci/screenshots.cjs:34:3) {
  name: 'Error'
}

Node.js v21.1.0
```

**Comment by signed-long** [comment]
> Got this even after `bun install`. Is it expected?
> 
> ```
> batman:new-connect$ node src/ci/screenshots.cjs http://localhost:3000
> node:internal/process/promises:289
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> 
> browserType.launch: Executable doesn't exist at /home/batman/.cache/ms-playwright/webkit-2003/pw_run.sh
> ╔═════════════════════════════════════════════════════════════════════════╗
> ║ Looks like Playwright Test or Playwright was just installed or updated. ║
> ║ Please run the following command to download new browsers:              ║
> ║                                                                         ║
> ║     npx playwright install                                              ║
> ║                                                                         ║
> ║ <3 Playwright Team                                                      ║
> ╚═════════════════════════════════════════════════════════════════════════╝
>     at /home/batman/src/new-connect/src/ci/screenshots.cjs:24:39
>     at Object.<anonymous> (/home/batman/src/new-connect/src/ci/screenshots.cjs:34:3) {
>   name: 'Error'
> }
> 
> Node.js v21.1.0
> ```

Ah yeah need to install the browser `bun playwright install webkit`

**Pull request merged**
